import * as React from 'react';

import ClientNavbarWrapper from "@/component/ClientNavbarWrapper";
import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { getServerSession } from "next-auth";
import SessionProvider from "@/utils/SessionProvider";
import Footer from '@/component/Footer';


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const session = await getServerSession();

  return (
    <html lang="en">
      <body className={`bg-slate-800 ${inter.className}`}>
        <SessionProvider session={session}>
          <div className="mx-auto max-w-5xl text-2xl gap-2 mb-10">
            <ClientNavbarWrapper /> {/* Use the client-side Navbar wrapper */}
            {children}
          </div>
          <Footer />
        </SessionProvider>
      </body>
    </html>
  );
}
